Need to auth and push release with gh CLI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,17 +90,23 @@ jobs:
           name: Build
           command: | # install env dependencies
             poetry build
-      - run:
-          name: Publish to PyPI
-          command: |
-            if test -z "${PYPI_USERNAME}" || test -z "${PYPI_PASSWORD}" ; then
-                echo "ERROR: Please assign PYPI_USERNAME and PYPI_PASSWORD as environment variables"
-                exit 1
-            fi
-            poetry publish --username=$PYPI_USERNAME --password=$PYPI_PASSWORD
+#      - run:
+#          name: Publish to PyPI
+#          command: |
+#            if test -z "${PYPI_USERNAME}" || test -z "${PYPI_PASSWORD}" ; then
+#                echo "ERROR: Please assign PYPI_USERNAME and PYPI_PASSWORD as environment variables"
+#                exit 1
+#            fi
+#            poetry publish --username=$PYPI_USERNAME --password=$PYPI_PASSWORD
       - run:
           name: Publish Github Release
           command: |
+            poetry install
+            PKG_VERSION=$(sed -n 's/^version = //p' pyproject.toml | sed -e 's/^"//' -e 's/"$//')
+            poetry run python scripts/print_version_changelog.py > ./version_changelog.md
+            echo $GH_TOKEN | gh auth login --with-token
+            gh release create v$PKG_VERSION dist/* -F ./version_changelog.md
+            
 
 workflows:
   nightly_build_test:
